---

- name: Installing core utils on
  hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: ansible_become_password
      prompt: Enter sudo password
      private: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    force_update: false
  tasks:
    - name: Install core pacman packages
      include_tasks: ../task-pacman-core.yml
